# Movie rating classification

## main purpose
Our main purpose  here given a set of movies and set of users rating the movies we want find model that
predict given a movie and user what the user will rate this movie

## data set
first we will install the data set

In [105]:
from google.colab import files
files.upload()

Saving cosine_similarity.py to cosine_similarity (2).py
Saving main.py to main (3).py
Saving matrix_factorization.py to matrix_factorization (3).py
Saving out to out (3)
Saving README.md to README (3).md
Saving resarch.ipynb to resarch (3).ipynb
Saving run to run (3)
Saving SGD_matrix_factorization.py to SGD_matrix_factorization (3).py
Saving two_tower.py to two_tower (2).py
Saving two_tower_model.py to two_tower_model (4).py

{'cosine_similarity (2).py': b'from sklearn.base import BaseEstimator, RegressorMixin\nfrom sklearn.metrics.pairwise import cosine_similarity\n\n\nclass ContentBasedModel(BaseEstimator, RegressorMixin):\n\n    def __init__(self, user_features, movie_features):\n        self.user_features = user_features\n        self.movie_features = movie_features\n\n    def fit(self, X, y):\n        return self\n\n    def predict(self, X):\n\n        user_id = X["userId"].iloc[0]\n\n        user_vector = self.user_features.loc[[user_id]]\n\n        scores = cosine_similarity(\n            user_vector,\n            self.movie_features\n        ).ravel()\n\n        return scores',
 'main (3).py': b'from two_tower_model import TwoTowerModel\nimport time \nimport pandas as pd\n\ndef build_movies():\n    pd.\n\ndef main():',
 'matrix_factorization (3).py': b'from sklearn.decomposition import NMF\nfrom scipy.sparse import csr_matrix\nimport numpy as np\n\n\nclass SparseNMF(NMF):\n\n    def __init__(\n        self,\n        num_of_movies,\n        n_components=20,\n        init=None,\n        solver="cd",\n        beta_loss="frobenius",\n        tol=1e-4,\n        max_iter=200,\n        random_state=None\n    ):\n        self.num_of_movies = num_of_movies\n        super().__init__(\n            n_components=n_components,\n            init=init,\n            solver=solver,\n            beta_loss=beta_loss,\n            tol=tol,\n            max_iter=max_iter,\n            random_state=random_state\n        )\n\n    def fit(self, X, y):\n\n        data = X.copy()\n        data["rating"] = y.values\n\n        self.user_ids_, user_idx = np.unique(\n            data["userId"].values,\n            return_inverse=True\n        )\n\n        self.movie_ids_, movie_idx = np.unique(\n            data["movieId"].values,\n            return_inverse=True\n        )\n\n        self.X_ = csr_matrix(\n            (\n                data["rating"].values,\n                (user_idx, movie_idx)\n            ),\n            shape=(\n                len(self.user_ids_),\n                self.num_of_movies\n            )\n        )\n\n        super().fit(self.X_)\n        self.W_ = super().fit_transform(self.X_)\n        return self\n\n    def predict(self, X):\n\n        user_idx = np.searchsorted(\n            self.user_ids_,\n            X["userId"].values\n        )\n\n        movie_idx = np.searchsorted(\n            self.movie_ids_,\n            X["movieId"].values\n        )\n\n        user_factors = self.W_[user_idx]\n\n        movie_factors = self.components_.T[movie_idx]\n\n        predictions = np.sum(\n            user_factors * movie_factors,\n            axis=1\n        )\n\n        predictions = np.clip(predictions, 0.5, 5)\n\n        return predictions',
 'out (3)': b'WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\nI0000 00:00:1787422507.293997   13673 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\nI0000 00:00:1787422507.358539   13673 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\nTo enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\nWARNING: All log messages before absl::InitializeLog() is called are written to STDERR\nI0000 00:00:1787422508.657792   13673 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n',
 'README (3).md': b'# movie-recommendation\nbuild a movie recommendation app base on the rank the user is given for other movies using ML\n',

In [106]:
%pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("grouplens/movielens-20m-dataset")

print("Path to dataset files:", path)

Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2026.7.22)
Using Colab cache for faster access to the 'movielens-20m-dataset' dataset.
Path to dataset files: /kaggle/input/movielens-20m-dataset

In [107]:
%pip install tensorflow
%pip install matplot
from matplotlib import pylab
#from google.colab import drive


import matplotlib.pyplot as plt
%pip install pandas
import pandas as pd
import sys
!{sys.executable} -m pip install scikit-learn
!{sys.executable} -m pip install seaborn
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sns

Requirement already satisfied: tensorflow in /usr/local/lib/python3.13/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.83.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Requirement already satisfied: matplot in /usr/local/lib/python3.13/dist-packages (0.1.9)
Requirement already satisfied: pyloco>=0.0.134 in /usr/local/lib/python3.13/dist-packages (from matplot) (0.0.139)
Requirement already satisfied: matplotlib>=3.1.1 in /usr/local/lib/python3.13/dist-packages (from matplot) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.1->matplot) (2.9.0.post0)
Requirement already satisfied: ushlex in /usr/local/lib/python3.13/dist-packages (from pyloco>=0.0.134->matplot) (0.99.1)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.13/dist-packages (from pyloco>=0.0.134->matplot) (1.9.0)
Requirement already satisfied: twine in /usr/local/lib/python3.13/dist-packages (from pyloco>=0.0.134->matplot) (7.0.0)
Requirement already satisfied: typing in /usr/local/lib/python3.13/dist-packages (from pyloco>=0.0.134->matplot) (3.7.4.3)
Requirement already satisfied: SimpleWebSocketServer in /usr/local/lib/python3.13/dist-packages (from pyloco>=0.0.134->matplot) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.1->matplot) (1.17.0)
Requirement already satisfied: readme-renderer>=35.0 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (45.0)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (2.32.4)
Requirement already satisfied: requests-toolbelt!=0.9.0,>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (1.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (2.5.0)
Requirement already satisfied: keyring>=21.2.0 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (25.7.0)
Requirement already satisfied: rfc3986>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (2.0.0)
Requirement already satisfied: rich>=14.3.3 in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (15.0.0)
Requirement already satisfied: id in /usr/local/lib/python3.13/dist-packages (from twine->pyloco>=0.0.134->matplot) (1.6.1)
Requirement already satisfied: SecretStorage>=3.2 in /usr/local/lib/python3.13/dist-packages (from keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (3.5.0)
Requirement already satisfied: jeepney>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (0.9.0)
Requirement already satisfied: jaraco.classes in /usr/local/lib/python3.13/dist-packages (from keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (3.4.0)
Requirement already satisfied: jaraco.functools in /usr/local/lib/python3.13/dist-packages (from keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (4.6.0)
Requirement already satisfied: jaraco.context in /usr/local/lib/python3.13/dist-packages (from keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (6.1.2)
Requirement already satisfied: nh3>=0.2.14 in /usr/local/lib/python3.13/dist-packages (from readme-renderer>=35.0->twine->pyloco>=0.0.134->matplot) (0.3.6)
Requirement already satisfied: docutils>=0.21.2 in /usr/local/lib/python3.13/dist-packages (from readme-renderer>=35.0->twine->pyloco>=0.0.134->matplot) (0.21.2)
Requirement already satisfied: Pygments>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from readme-renderer>=35.0->twine->pyloco>=0.0.134->matplot) (2.21.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20->twine->pyloco>=0.0.134->matplot) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20->twine->pyloco>=0.0.134->matplot) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.20->twine->pyloco>=0.0.134->matplot) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=14.3.3->twine->pyloco>=0.0.134->matplot) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=14.3.3->twine->pyloco>=0.0.134->matplot) (0.1.2)
Requirement already satisfied: cryptography>=2.0 in /usr/local/lib/python3.13/dist-packages (from SecretStorage>=3.2->keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (50.0.0)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.13/dist-packages (from jaraco.classes->keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (10.8.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->twine->pyloco>=0.0.134->matplot) (3.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.13/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

### this are the files we get from kaggle:

In [108]:
import os
print(os.listdir(path))

['rating.csv', 'link.csv', 'genome_tags.csv', 'genome_scores.csv', 'tag.csv', 'movie.csv']

### rating

In [109]:
ratings = pd.read_csv(os.path.join(path, 'rating.csv'), nrows=1_000_000
)
ratings = ratings.drop(columns=['timestamp'])
ratings.head(5)

   userId  movieId  rating
0       1        2     3.5
1       1       29     3.5
2       1       32     3.5
3       1       47     3.5
4       1       50     3.5

### movies

In [110]:
movies = pd.read_csv(os.path.join(path, 'movie.csv'))
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

## Normalizations

### Encode genres

In [111]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
if "genres" in movies.columns:
    genre_features = mlb.fit_transform(movies['genres'].str.split('|'))
    genre_df = pd.DataFrame(
        genre_features,
        columns=mlb.classes_,
        index=movies.index
    )

    movies = pd.concat(
        [movies[["movieId"]], genre_df],
        axis=1
    )
movies.head(5)

,movieId,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,0,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4,5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Learing

now we will suggest a learning algorithm for this problem

In [112]:
X_train, X_test, y_train, y_test = train_test_split(
    ratings[["userId", "movieId"]],
    ratings["rating"],
    test_size=0.2,
    random_state=42
)

## LinerRegression

In [113]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

### score

In [114]:
def print_error(model, X_train, y_train, X_test, y_test):
    from sklearn.metrics import mean_absolute_error, mean_squared_error

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_mae = mean_absolute_error(y_train, train_pred)
    test_mae = mean_absolute_error(y_test, test_pred)

    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5

    print("Train MAE:", train_mae)
    print("Test MAE:", test_mae)
    print("Train RMSE:", train_rmse)
    print("Test RMSE:", test_rmse)

print_error(model, X_train, y_train, X_test, y_test)

Train MAE: 0.8405564838565901
Test MAE: 0.8396936110796265
Train RMSE: 1.0522522023096548
Test RMSE: 1.051267197872636

As we can see we get a bad RMSE so we need to choose another model class

## Matrix Factorization

In [115]:

from matrix_factorization import SparseNMF

model = SparseNMF(movies.shape[0])
model.fit(X_train,y_train)

SparseNMF(num_of_movies=27278)

## Testing

In [116]:
from sklearn.metrics import mean_squared_error

def print_RMSE(model,X_train,X_test,y_train,y_test):
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_mse = np.sqrt(mean_squared_error(y_train, train_pred))
    test_mse = np.sqrt(mean_squared_error(y_test, test_pred))

    print("Train RMSE:", train_mse)
    print("Test RMSE:", test_mse)

print_RMSE(model,X_train,X_test,y_train,y_test)

Train RMSE: 2.6516475508306607
Test RMSE: 2.7035846623622786

As we can see this soultion doesn't work well against LinearRegression. In addition this model is not that scaleable because we use a constant matrix.

## SGD Matrix Factorization

In [117]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.13/dist-packages (1.1.5)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.13/dist-packages (from scikit-surprise) (2.1.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from scikit-surprise) (1.16.3)

In [118]:
from SGD_matrix_factorization import SGDMatrixFacorization

model = SGDMatrixFacorization(rating_scale=(0.0,5.0))
model.fit(X_train,y_train)

SGDMatrixFacorization(rating_scale=(0.0, 5.0))

## testing

In [119]:
known_movies = set(model.model.trainset._raw2inner_id_items.keys())

mask = X_test["movieId"].isin(known_movies)

X_test_filtered = X_test[mask]
y_test_filtered = y_test[mask]

print_RMSE(model=model,X_train=X_train,X_test=X_test_filtered,y_train=y_train,y_test=y_test_filtered)

Train RMSE: 0.5366949138863938
Test RMSE: 0.8468428807052385

As we can see, the model achieves good performance. However, it requires all users and movies to be known during training. Therefore, it cannot naturally make predictions for previously unseen movies or users (the cold-start problem).

## Two Tower

we need to repreasent users base on what they like

In [120]:
gerners = movies.drop(columns=["movieId"])
genre_counts = gerners.sum()
genre_counts

(no genres listed)      246
Action                 3520
Adventure              2329
Animation              1027
Children               1139
Comedy                 8374
Crime                  2939
Documentary            2471
Drama                 13344
Fantasy                1412
Film-Noir               330
Horror                 2611
IMAX                    196
Musical                1036
Mystery                1514
Romance                4127
Sci-Fi                 1743
Thriller               4178
War                    1194
Western                 676
dtype: int64

In [121]:
user_genre = ratings.merge(movies, on="movieId")
genre_columns = gerners.columns.to_list()

user_genre_matrix = pd.DataFrame(index=user_genre["userId"].unique())

for genre in genre_columns:
    user_genre_matrix[genre] = (
        user_genre[user_genre[genre] == 1]
        .groupby("userId")["rating"]
        .mean()
    )
genre_means = user_genre_matrix.mean()
user_genre_matrix = user_genre_matrix.fillna(genre_means)
user_genre_matrix

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
1,3.333333,3.727273,3.787671,3.650000,3.605263,3.731707,3.809524,3.773979,3.767442,3.789855,3.900266,3.744444,4.250000,3.666667,3.611111,3.954545,3.712500,3.761905,3.666667,3.375000
2,3.333333,4.631579,4.823529,3.000000,3.000000,3.900000,5.000000,3.773979,3.894737,2.000000,5.000000,3.555556,3.000000,3.000000,4.500000,3.833333,4.608696,4.263158,4.250000,4.500000
3,3.333333,4.114754,4.220000,3.750000,4.300000,4.057692,4.285714,4.000000,4.224138,4.300000,3.000000,3.937500,3.734584,4.000000,4.363636,4.062500,4.000000,4.260000,4.666667,4.333333
4,3.333333,3.538462,3.833333,4.000000,3.750000,3.545455,3.166667,3.773979,3.750000,3.666667,3.900266,3.416261,3.734584,4.000000,2.666667,3.500000,3.000000,3.461538,4.000000,4.000000
5,3.333333,4.500000,4.523810,4.666667,4.181818,4.083333,4.142857,3.773979,4.185185,3.727273,3.900266,3.000000,5.000000,4.375000,3.500000,3.937500,4.600000,4.333333,4.000000,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6739,3.333333,2.135514,1.989950,1.761905,1.595745,2.455385,3.067164,3.200000,2.970899,2.173469,4.050000,2.118110,2.000000,1.918367,3.132353,2.569343,2.167785,2.635628,3.222222,2.388889
6740,3.333333,4.000000,4.000000,5.000000,5.000000,3.650000,4.166667,3.773979,3.772727,3.875000,3.900266,3.416261,3.734584,3.549957,4.000000,3.928571,3.000000,3.750000,3.875000,4.500000
6741,3.333333,3.250000,3.660000,4.090909,3.900000,4.103448,4.083333,4.000000,3.865385,3.725000,3.000000,4.500000,3.600000,3.687500,3.900000,3.937500,3.800000,4.045455,4.000000,3.570488
6742,3.333333,3.500000,4.000000,3.615842,3.453785,4.500000,4.000000,3.773979,4.625000,5.000000,3.900266,3.416261,5.000000,3.549957,3.719430,4.200000,3.466998,4.000000,4.666667,3.000000
6743,3.333333,3.333333,3.311321,3.625000,3.000000,3.065934,3.750000,3.773979,3.464286,3.225806,3.900266,3.547619,3.166667,3.650000,3.750000,3.093750,3.308511,3.440678,3.785714,3.416667

In [122]:
if "movieId" in movies.columns:
    movies = movies.set_index("movieId")

In [123]:
from two_tower_model import TwoTowerModel
embedding_dim = 32
batch_size = 4*1024
epochs = 5
model = TwoTowerModel(user_features=user_genre_matrix,movie_features=movies,
                      epochs=epochs,batch_size=batch_size,embedding_dim=embedding_dim)
model.fit(X_train,y_train)

Epoch 1/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 8s 26ms/step - loss: 1.1522 - root_mean_squared_error: 1.0734 - val_loss: 0.8539 - val_root_mean_squared_error: 0.9241
Epoch 2/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.8385 - root_mean_squared_error: 0.9157 - val_loss: 0.8281 - val_root_mean_squared_error: 0.9100
Epoch 3/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.8160 - root_mean_squared_error: 0.9034 - val_loss: 0.8068 - val_root_mean_squared_error: 0.8982
Epoch 4/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.8029 - root_mean_squared_error: 0.8960 - val_loss: 0.7972 - val_root_mean_squared_error: 0.8929
Epoch 5/5
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.7943 - root_mean_squared_error: 0.8912 - val_loss: 0.7884 - val_root_mean_squared_error: 0.8879

TwoTowerModel(batch_size=4096, embedding_dim=32, epochs=5,
              movie_features=array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32),
              user_features=array([[3.3333333, 3.7272727, 3.7876713, ..., 3.7619047, 3.6666667,
        3.375    ],
       [3.3333333, 4.631579 , 4.8235292, ..., 4.263158 , 4.25     ,
        4.5      ],
       [3.3333333, 4.114754 , 4.22     , ..., 4.26     , 4.6666665,
        4.3333335],
       ...,
       [3.3333333, 3.25     , 3.66     , ..., 4.0454545, 4.       ,
        3.5704882],
       [3.3333333, 3.5      , 4.       , ..., 4.       , 4.6666665,
        3.       ],
       [3.3333333, 3.3333333, 3.3113208, ..., 3.440678 , 3.7857144,
        3.4166667]], dtype=float32))

## Testing

In [124]:
print_RMSE(model,X_train,X_test,y_train,y_test)

Train RMSE: 0.887891134850858
Test RMSE: 0.8855830758908975

## Tunning
lets do tunning for the model

In [125]:
from two_tower_model import TwoTowerModel
learning_rates = [
    1e-4,
    3e-4,
    1e-3,
    3e-3,
    1e-2
]

embedding_dim = 32
batch_size = 4*1024
epochs = 7
model = TwoTowerModel(user_features=user_genre_matrix,movie_features=movies,
                      epochs=epochs,batch_size=batch_size,embedding_dim=embedding_dim,
                      learning_rate= learning_rates[3])
model.fit(X_train,y_train)

Epoch 1/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 1.0794 - root_mean_squared_error: 1.0390 - val_loss: 0.8363 - val_root_mean_squared_error: 0.9145
Epoch 2/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.8237 - root_mean_squared_error: 0.9076 - val_loss: 0.8153 - val_root_mean_squared_error: 0.9029
Epoch 3/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.8033 - root_mean_squared_error: 0.8963 - val_loss: 0.7983 - val_root_mean_squared_error: 0.8935
Epoch 4/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.7928 - root_mean_squared_error: 0.8904 - val_loss: 0.7787 - val_root_mean_squared_error: 0.8824
Epoch 5/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.7855 - root_mean_squared_error: 0.8863 - val_loss: 0.7761 - val_root_mean_squared_error: 0.8810
Epoch 6/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.7757 - root_mean_squared_error: 0.8807 - val_loss: 0.7777 - val_root_mean_squared_error: 0.8819
Epoch 7/7
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.7741 - root_mean_squared_error: 0.8798 - val_loss: 0.7745 - val_root_mean_squared_error: 0.8800

TwoTowerModel(batch_size=4096, embedding_dim=32, epochs=7, learning_rate=0.003,
              movie_features=array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32),
              user_features=array([[3.3333333, 3.7272727, 3.7876713, ..., 3.7619047, 3.6666667,
        3.375    ],
       [3.3333333, 4.631579 , 4.8235292, ..., 4.263158 , 4.25     ,
        4.5      ],
       [3.3333333, 4.114754 , 4.22     , ..., 4.26     , 4.6666665,
        4.3333335],
       ...,
       [3.3333333, 3.25     , 3.66     , ..., 4.0454545, 4.       ,
        3.5704882],
       [3.3333333, 3.5      , 4.       , ..., 4.       , 4.6666665,
        3.       ],
       [3.3333333, 3.3333333, 3.3113208, ..., 3.440678 , 3.7857144,
        3.4166667]], dtype=float32))

In [126]:
print_RMSE(model,X_train,X_test,y_train,y_test)

Train RMSE: 0.8793016362064804
Test RMSE: 0.8761539215945888